Add copy/paste to tileset editor
huderlem/porymap pull request #425
Opened 2022-03-30 22:49 UTC by GriffinRichards

Also renames two definitions of `getSelectedMetatile` to `getSelectedMetatileId`

Closes #421 
Also somewhat addresses #292

2022-06-28 17:50 UTC, garakmon requested changes

2022-06-29 20:48 UTC, GriffinRichards commented on src/ui/tileseteditor.cpp
> +    if (!this->replaceMetatile(metatileId, this->copiedMetatile))
Updated. Deleting `prevMetatile` shouldn't be necessary. The `MetatileHistoryItem` will handle that, and needs it in the meantime.

2022-06-29 22:30 UTC, garakmon commented on src/ui/tileseteditor.cpp
> +    if (!this->replaceMetatile(metatileId, this->copiedMetatile))
I meant before the return

2022-06-29 22:34 UTC, GriffinRichards commented on src/ui/tileseteditor.cpp
> +    if (!this->replaceMetatile(metatileId, this->copiedMetatile))
So did I. `MetatileHistoryItem` is responsible for deleting it, same as all the other uses in this file.

2022-06-29 23:12 UTC, garakmon approved these changes

2022-06-29 23:13 UTC, merged